[package]
name = "rollup-node-sequencer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-provider = { workspace = true, features = ["engine-api"] }
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# scroll reth
dogeos-reth-engine.workspace = true
dogeos-reth-primitives.workspace = true

# DogeOS protocol
dogeos-protocol-types.workspace = true
dogeos-hardforks.workspace = true
dogeos-rpc-types.workspace = true

# rollup-node
scroll-db = { workspace = true }
scroll-engine.workspace = true
rollup-node-providers.workspace = true
rollup-node-primitives.workspace = true

# misc
futures.workspace = true
metrics.workspace = true
metrics-derive.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
eyre.workspace = true

[dev-dependencies]
# alloy
alloy-primitives.workspace = true

rollup-node-signer.workspace = true

# reth
reth-e2e-test-utils.workspace = true
reth-node-core.workspace = true
reth-tasks.workspace = true
reth-tracing.workspace = true

dogeos-chainspec.workspace = true

# rollup-node
rollup-node = { workspace = true, features = ["test-utils"] }
rollup-node-chain-orchestrator.workspace = true
rollup-node-primitives.workspace = true
rollup-node-providers = { workspace = true, features = ["test-utils"] }
rollup-node-sequencer.workspace = true
rollup-node-watcher.workspace = true
scroll-db = { workspace = true, features = ["test-utils"] }
scroll-engine.workspace = true

# misc
futures.workspace = true
tempfile = "3.20.0"
alloy-signer-local.workspace = true
