[package]
name = "scroll-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-chains.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-provider = { workspace = true, features = ["engine-api"] }
alloy-rpc-types-engine.workspace = true
alloy-transport.workspace = true

# DogeOS protocol
dogeos-hardforks.workspace = true
dogeos-rpc-types.workspace = true
dogeos-reth-engine.workspace = true

# reth
reth-chainspec.workspace = true
reth-network-api.workspace = true
reth-payload-primitives.workspace = true
reth-primitives-traits.workspace = true

dogeos-chainspec.workspace = true
dogeos-reth-primitives.workspace = true

# rollup-node
rollup-node-primitives.workspace = true

# misc
async-trait.workspace = true
eyre.workspace = true
futures.workspace = true
metrics.workspace = true
metrics-derive.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
jsonrpsee = { version = "0.26.0", features = ["client"] }

[dev-dependencies]
alloy-consensus.workspace = true
arbitrary.workspace = true
async-trait.workspace = true
reth-testing-utils.workspace = true
dogeos-protocol-types = { workspace = true, features = ["arbitrary"] }
dogeos-reth-engine.workspace = true

[features]
test-utils = [
    "reth-chainspec/test-utils",
    "reth-primitives-traits/test-utils",
]
serde = [
    "dep:serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "alloy-rpc-types-engine/serde",
    "dogeos-reth-primitives/serde",
    "alloy-chains/serde",
    "reth-network-api/serde",
    "dogeos-hardforks/serde",
    "reth-primitives-traits/serde",
    "alloy-consensus/serde",
    "dogeos-protocol-types/serde",
    "rollup-node-primitives/serde",
]
